// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/database/habit_entity.dart';
import 'data/database/habit_entry_entity.dart';
import 'data/database/habit_limit_entity.dart';
import 'data/database/habit_schedule_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 573904481184556594),
    name: 'HabitEntity',
    lastPropertyId: const obx_int.IdUid(10, 2670188055364762326),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1319189913911486811),
        name: 'obId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7994893434822550204),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 4000399812115691134),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7373897724264342342),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8397818970998185383),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4896759246395696238),
        name: 'unit',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3233159499228635376),
        name: 'targetValue',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8097592847452607485),
        name: 'colorHex',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 9193291435403199984),
        name: 'iconName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7056154650241883872),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2670188055364762326),
        name: 'isArchived',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 1576902478958345771),
        name: 'entries',
        targetId: const obx_int.IdUid(2, 7270468841218197411),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 8911788270296820664),
        name: 'limits',
        targetId: const obx_int.IdUid(3, 2351230427218951919),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(3, 1994842980754943346),
        name: 'schedules',
        targetId: const obx_int.IdUid(4, 4949055564855433280),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7270468841218197411),
    name: 'HabitEntryEntity',
    lastPropertyId: const obx_int.IdUid(8, 8051186685253687205),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 199341000485935701),
        name: 'obId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2495815665159480613),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 2929817633120900538),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1853518911165016646),
        name: 'habitId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 7559051510036612446),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8395650495486155885),
        name: 'date',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5727197829065924138),
        name: 'value',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8182861363365812859),
        name: 'note',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3683551108326231562),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8051186685253687205),
        name: 'habitEntityId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(8, 452708837900837499),
        relationTarget: 'HabitEntity',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 2351230427218951919),
    name: 'HabitLimitEntity',
    lastPropertyId: const obx_int.IdUid(8, 3592472940850790824),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6162794246145707695),
        name: 'obId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8940765371604071877),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 4015351276567415038),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6089280998596095484),
        name: 'habitId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 1348981944105808181),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2332617046298988374),
        name: 'minValue',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3008879668067480424),
        name: 'maxValue',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2335213100047645508),
        name: 'effectiveFrom',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3447234925971875943),
        name: 'effectiveTo',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3592472940850790824),
        name: 'habitEntityId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(9, 2017521833977215652),
        relationTarget: 'HabitEntity',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 4949055564855433280),
    name: 'HabitScheduleEntity',
    lastPropertyId: const obx_int.IdUid(9, 1554382774578784439),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7114162478748547848),
        name: 'obId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3896800405334163375),
        name: 'id',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(6, 7651739384994388124),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2390492813440680550),
        name: 'habitId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(7, 941017925296588415),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 340920481937363122),
        name: 'scheduleType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5675944086218362923),
        name: 'scheduledWeekdays',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3970098139747918476),
        name: 'targetCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5300861930919708352),
        name: 'effectiveFrom',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 415063781343761503),
        name: 'effectiveTo',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1554382774578784439),
        name: 'habitEntityId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(10, 835623659848710079),
        relationTarget: 'HabitEntity',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 4949055564855433280),
    lastIndexId: const obx_int.IdUid(10, 835623659848710079),
    lastRelationId: const obx_int.IdUid(3, 1994842980754943346),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    HabitEntity: obx_int.EntityDefinition<HabitEntity>(
      model: _entities[0],
      toOneRelations: (HabitEntity object) => [],
      toManyRelations: (HabitEntity object) => {
        obx_int.RelInfo<HabitEntity>.toMany(1, object.obId): object.entries,
        obx_int.RelInfo<HabitEntity>.toMany(2, object.obId): object.limits,
        obx_int.RelInfo<HabitEntity>.toMany(3, object.obId): object.schedules,
      },
      getId: (HabitEntity object) => object.obId,
      setId: (HabitEntity object, int id) {
        object.obId = id;
      },
      objectToFB: (HabitEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final nameOffset = fbb.writeString(object.name);
        final typeOffset = fbb.writeString(object.type);
        final unitOffset = object.unit == null
            ? null
            : fbb.writeString(object.unit!);
        final colorHexOffset = fbb.writeString(object.colorHex);
        final iconNameOffset = fbb.writeString(object.iconName);
        fbb.startTable(11);
        fbb.addInt64(0, object.obId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, typeOffset);
        fbb.addOffset(4, unitOffset);
        fbb.addFloat64(5, object.targetValue);
        fbb.addOffset(6, colorHexOffset);
        fbb.addOffset(7, iconNameOffset);
        fbb.addInt64(8, object.createdAt);
        fbb.addBool(9, object.isArchived);
        fbb.finish(fbb.endTable());
        return object.obId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final unitParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final targetValueParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final colorHexParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final iconNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final createdAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final isArchivedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final object = HabitEntity(
          obId: obIdParam,
          id: idParam,
          name: nameParam,
          type: typeParam,
          unit: unitParam,
          targetValue: targetValueParam,
          colorHex: colorHexParam,
          iconName: iconNameParam,
          createdAt: createdAtParam,
          isArchived: isArchivedParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<HabitEntity>(
          object.entries,
          store,
          obx_int.RelInfo<HabitEntity>.toMany(1, object.obId),
        );
        obx_int.InternalToManyAccess.setRelInfo<HabitEntity>(
          object.limits,
          store,
          obx_int.RelInfo<HabitEntity>.toMany(2, object.obId),
        );
        obx_int.InternalToManyAccess.setRelInfo<HabitEntity>(
          object.schedules,
          store,
          obx_int.RelInfo<HabitEntity>.toMany(3, object.obId),
        );
        return object;
      },
    ),
    HabitEntryEntity: obx_int.EntityDefinition<HabitEntryEntity>(
      model: _entities[1],
      toOneRelations: (HabitEntryEntity object) => [object.habitEntity],
      toManyRelations: (HabitEntryEntity object) => {},
      getId: (HabitEntryEntity object) => object.obId,
      setId: (HabitEntryEntity object, int id) {
        object.obId = id;
      },
      objectToFB: (HabitEntryEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final habitIdOffset = fbb.writeString(object.habitId);
        final noteOffset = object.note == null
            ? null
            : fbb.writeString(object.note!);
        fbb.startTable(9);
        fbb.addInt64(0, object.obId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, habitIdOffset);
        fbb.addInt64(3, object.date);
        fbb.addFloat64(4, object.value);
        fbb.addOffset(5, noteOffset);
        fbb.addInt64(6, object.createdAt);
        fbb.addInt64(7, object.habitEntity.targetId);
        fbb.finish(fbb.endTable());
        return object.obId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final habitIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final dateParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final valueParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final noteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final createdAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = HabitEntryEntity(
          obId: obIdParam,
          id: idParam,
          habitId: habitIdParam,
          date: dateParam,
          value: valueParam,
          note: noteParam,
          createdAt: createdAtParam,
        );
        object.habitEntity.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        object.habitEntity.attach(store);
        return object;
      },
    ),
    HabitLimitEntity: obx_int.EntityDefinition<HabitLimitEntity>(
      model: _entities[2],
      toOneRelations: (HabitLimitEntity object) => [object.habitEntity],
      toManyRelations: (HabitLimitEntity object) => {},
      getId: (HabitLimitEntity object) => object.obId,
      setId: (HabitLimitEntity object, int id) {
        object.obId = id;
      },
      objectToFB: (HabitLimitEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final habitIdOffset = fbb.writeString(object.habitId);
        fbb.startTable(9);
        fbb.addInt64(0, object.obId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, habitIdOffset);
        fbb.addFloat64(3, object.minValue);
        fbb.addFloat64(4, object.maxValue);
        fbb.addInt64(5, object.effectiveFrom);
        fbb.addInt64(6, object.effectiveTo);
        fbb.addInt64(7, object.habitEntity.targetId);
        fbb.finish(fbb.endTable());
        return object.obId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final habitIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final minValueParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final maxValueParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final effectiveFromParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final effectiveToParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final object = HabitLimitEntity(
          obId: obIdParam,
          id: idParam,
          habitId: habitIdParam,
          minValue: minValueParam,
          maxValue: maxValueParam,
          effectiveFrom: effectiveFromParam,
          effectiveTo: effectiveToParam,
        );
        object.habitEntity.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        object.habitEntity.attach(store);
        return object;
      },
    ),
    HabitScheduleEntity: obx_int.EntityDefinition<HabitScheduleEntity>(
      model: _entities[3],
      toOneRelations: (HabitScheduleEntity object) => [object.habitEntity],
      toManyRelations: (HabitScheduleEntity object) => {},
      getId: (HabitScheduleEntity object) => object.obId,
      setId: (HabitScheduleEntity object, int id) {
        object.obId = id;
      },
      objectToFB: (HabitScheduleEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final habitIdOffset = fbb.writeString(object.habitId);
        final scheduleTypeOffset = fbb.writeString(object.scheduleType);
        final scheduledWeekdaysOffset = object.scheduledWeekdays == null
            ? null
            : fbb.writeList(
                object.scheduledWeekdays!
                    .map(fbb.writeString)
                    .toList(growable: false),
              );
        fbb.startTable(10);
        fbb.addInt64(0, object.obId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, habitIdOffset);
        fbb.addOffset(3, scheduleTypeOffset);
        fbb.addOffset(4, scheduledWeekdaysOffset);
        fbb.addInt64(5, object.targetCount);
        fbb.addInt64(6, object.effectiveFrom);
        fbb.addInt64(7, object.effectiveTo);
        fbb.addInt64(8, object.habitEntity.targetId);
        fbb.finish(fbb.endTable());
        return object.obId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final habitIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final scheduleTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final scheduledWeekdaysParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final targetCountParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final effectiveFromParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final effectiveToParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final object = HabitScheduleEntity(
          obId: obIdParam,
          id: idParam,
          habitId: habitIdParam,
          scheduleType: scheduleTypeParam,
          scheduledWeekdays: scheduledWeekdaysParam,
          targetCount: targetCountParam,
          effectiveFrom: effectiveFromParam,
          effectiveTo: effectiveToParam,
        );
        object.habitEntity.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        object.habitEntity.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [HabitEntity] entity fields to define ObjectBox queries.
class HabitEntity_ {
  /// See [HabitEntity.obId].
  static final obId = obx.QueryIntegerProperty<HabitEntity>(
    _entities[0].properties[0],
  );

  /// See [HabitEntity.id].
  static final id = obx.QueryStringProperty<HabitEntity>(
    _entities[0].properties[1],
  );

  /// See [HabitEntity.name].
  static final name = obx.QueryStringProperty<HabitEntity>(
    _entities[0].properties[2],
  );

  /// See [HabitEntity.type].
  static final type = obx.QueryStringProperty<HabitEntity>(
    _entities[0].properties[3],
  );

  /// See [HabitEntity.unit].
  static final unit = obx.QueryStringProperty<HabitEntity>(
    _entities[0].properties[4],
  );

  /// See [HabitEntity.targetValue].
  static final targetValue = obx.QueryDoubleProperty<HabitEntity>(
    _entities[0].properties[5],
  );

  /// See [HabitEntity.colorHex].
  static final colorHex = obx.QueryStringProperty<HabitEntity>(
    _entities[0].properties[6],
  );

  /// See [HabitEntity.iconName].
  static final iconName = obx.QueryStringProperty<HabitEntity>(
    _entities[0].properties[7],
  );

  /// See [HabitEntity.createdAt].
  static final createdAt = obx.QueryIntegerProperty<HabitEntity>(
    _entities[0].properties[8],
  );

  /// See [HabitEntity.isArchived].
  static final isArchived = obx.QueryBooleanProperty<HabitEntity>(
    _entities[0].properties[9],
  );

  /// see [HabitEntity.entries]
  static final entries = obx.QueryRelationToMany<HabitEntity, HabitEntryEntity>(
    _entities[0].relations[0],
  );

  /// see [HabitEntity.limits]
  static final limits = obx.QueryRelationToMany<HabitEntity, HabitLimitEntity>(
    _entities[0].relations[1],
  );

  /// see [HabitEntity.schedules]
  static final schedules =
      obx.QueryRelationToMany<HabitEntity, HabitScheduleEntity>(
        _entities[0].relations[2],
      );
}

/// [HabitEntryEntity] entity fields to define ObjectBox queries.
class HabitEntryEntity_ {
  /// See [HabitEntryEntity.obId].
  static final obId = obx.QueryIntegerProperty<HabitEntryEntity>(
    _entities[1].properties[0],
  );

  /// See [HabitEntryEntity.id].
  static final id = obx.QueryStringProperty<HabitEntryEntity>(
    _entities[1].properties[1],
  );

  /// See [HabitEntryEntity.habitId].
  static final habitId = obx.QueryStringProperty<HabitEntryEntity>(
    _entities[1].properties[2],
  );

  /// See [HabitEntryEntity.date].
  static final date = obx.QueryIntegerProperty<HabitEntryEntity>(
    _entities[1].properties[3],
  );

  /// See [HabitEntryEntity.value].
  static final value = obx.QueryDoubleProperty<HabitEntryEntity>(
    _entities[1].properties[4],
  );

  /// See [HabitEntryEntity.note].
  static final note = obx.QueryStringProperty<HabitEntryEntity>(
    _entities[1].properties[5],
  );

  /// See [HabitEntryEntity.createdAt].
  static final createdAt = obx.QueryIntegerProperty<HabitEntryEntity>(
    _entities[1].properties[6],
  );

  /// See [HabitEntryEntity.habitEntity].
  static final habitEntity =
      obx.QueryRelationToOne<HabitEntryEntity, HabitEntity>(
        _entities[1].properties[7],
      );
}

/// [HabitLimitEntity] entity fields to define ObjectBox queries.
class HabitLimitEntity_ {
  /// See [HabitLimitEntity.obId].
  static final obId = obx.QueryIntegerProperty<HabitLimitEntity>(
    _entities[2].properties[0],
  );

  /// See [HabitLimitEntity.id].
  static final id = obx.QueryStringProperty<HabitLimitEntity>(
    _entities[2].properties[1],
  );

  /// See [HabitLimitEntity.habitId].
  static final habitId = obx.QueryStringProperty<HabitLimitEntity>(
    _entities[2].properties[2],
  );

  /// See [HabitLimitEntity.minValue].
  static final minValue = obx.QueryDoubleProperty<HabitLimitEntity>(
    _entities[2].properties[3],
  );

  /// See [HabitLimitEntity.maxValue].
  static final maxValue = obx.QueryDoubleProperty<HabitLimitEntity>(
    _entities[2].properties[4],
  );

  /// See [HabitLimitEntity.effectiveFrom].
  static final effectiveFrom = obx.QueryIntegerProperty<HabitLimitEntity>(
    _entities[2].properties[5],
  );

  /// See [HabitLimitEntity.effectiveTo].
  static final effectiveTo = obx.QueryIntegerProperty<HabitLimitEntity>(
    _entities[2].properties[6],
  );

  /// See [HabitLimitEntity.habitEntity].
  static final habitEntity =
      obx.QueryRelationToOne<HabitLimitEntity, HabitEntity>(
        _entities[2].properties[7],
      );
}

/// [HabitScheduleEntity] entity fields to define ObjectBox queries.
class HabitScheduleEntity_ {
  /// See [HabitScheduleEntity.obId].
  static final obId = obx.QueryIntegerProperty<HabitScheduleEntity>(
    _entities[3].properties[0],
  );

  /// See [HabitScheduleEntity.id].
  static final id = obx.QueryStringProperty<HabitScheduleEntity>(
    _entities[3].properties[1],
  );

  /// See [HabitScheduleEntity.habitId].
  static final habitId = obx.QueryStringProperty<HabitScheduleEntity>(
    _entities[3].properties[2],
  );

  /// See [HabitScheduleEntity.scheduleType].
  static final scheduleType = obx.QueryStringProperty<HabitScheduleEntity>(
    _entities[3].properties[3],
  );

  /// See [HabitScheduleEntity.scheduledWeekdays].
  static final scheduledWeekdays =
      obx.QueryStringVectorProperty<HabitScheduleEntity>(
        _entities[3].properties[4],
      );

  /// See [HabitScheduleEntity.targetCount].
  static final targetCount = obx.QueryIntegerProperty<HabitScheduleEntity>(
    _entities[3].properties[5],
  );

  /// See [HabitScheduleEntity.effectiveFrom].
  static final effectiveFrom = obx.QueryIntegerProperty<HabitScheduleEntity>(
    _entities[3].properties[6],
  );

  /// See [HabitScheduleEntity.effectiveTo].
  static final effectiveTo = obx.QueryIntegerProperty<HabitScheduleEntity>(
    _entities[3].properties[7],
  );

  /// See [HabitScheduleEntity.habitEntity].
  static final habitEntity =
      obx.QueryRelationToOne<HabitScheduleEntity, HabitEntity>(
        _entities[3].properties[8],
      );
}
